# Welcome to Serverless!
# For full config options, check the docs:
#    docs.serverless.com

service: covid-supply-estimator-api
frameworkVersion: ">=1.40.0 <2.0.0"
# app: my-first-app # change app_id
# org: cupurion234 # change organization

## app and org for use with dashboard.serverless.com
# service: helloworld
app: cocast-serverless-seir-api
org: cocast

provider:
  name: aws
  runtime: python3.8

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

environment:
  variable1: value1

functions:
  supply-estimation:
    handler: handler.supply_estimation
    events:
      - http:
          path: api/supply-estimation
          method: post
          cors: true
  supply-service:
    handler: handler.supply_service
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: api/supply-service
          method: post
          cors: true
package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: non-linux
